### ISSUE TITLE
go the other way?

### ISSUE THREAD

**Issue by beren12** [needlestack/caption-converters#1]
Do you feel like making a util to go from webvtt back to srt?

**Comment by needlestack** [comment]
If there is a need I could probably put something together... is this an official request? :)

**Comment by beren12** [comment]
It would be great, I'm currently using a webpage to convert from one to the other

**Comment by needlestack** [comment]
OK, I have added vtt2srt.pl. It doesn't try to do anything clever with the formatting. Hope it works for you.

**Comment by beren12** [comment]
Great, thanks!
